update workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,9 +44,12 @@ jobs:
         env: 
           POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
           LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
-      - name: List dist directory
+      - name: Verify build
         run: |
-          ls dist -la
+          if [ ! -f "dist/swingmusic" ]; then
+            echo "Build failed"
+            exit 1
+          fi
       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
